import { Module } from '@nestjs/common';
import {
  UtilsModule,
  WsConfigModule,
  WsCacheModule,
  WsCasbinModule,
  WsWinstonModule,
  DatabaseModule,
  WsClickhouseModule,
  WsMulterModule,
  WsRedisModule,
  WsJwtModule,
  WsHttpModule,
  WsThrottlerModule,
  WsEventEmitterModule,
  GatewaysModule,
  WsScheduleModule,
} from '@weishour/core/modules';

@Module({
  imports: [
    UtilsModule,
    WsConfigModule,
    WsCacheModule,
    WsCasbinModule,
    WsWinstonModule,
    DatabaseModule,
    WsClickhouseModule,
    WsMulterModule,
    WsRedisModule,
    WsJwtModule,
    WsHttpModule,
    WsThrottlerModule,
    WsEventEmitterModule,
    GatewaysModule,
    WsScheduleModule,
  ],
  exports: [
    UtilsModule,
    WsConfigModule,
    WsCacheModule,
    WsCasbinModule,
    WsWinstonModule,
    DatabaseModule,
    WsClickhouseModule,
    WsMulterModule,
    WsRedisModule,
    WsJwtModule,
    WsHttpModule,
    WsThrottlerModule,
    WsEventEmitterModule,
    GatewaysModule,
    WsScheduleModule,
  ],
})
export class CoreModule {}
